### ISSUE TITLE
Incorrect rendering on 4.0.rc1

### ISSUE THREAD

**Issue by Calinou** [Nordup/godot-path-tracing#2]
**OS:** Fedora 37
**GPU:** NVIDIA GeForce RTX 4090 (NVIDIA 525.85.01)

Rendering appears mostly green, even though pathtracing does work technically:

### Ray depth 5 (default)

![image](https://user-images.githubusercontent.com/180032/218329757-0d8ee151-4c0f-46c8-9d4f-edc3a255b113.png)

### Ray depth 1

![image](https://user-images.githubusercontent.com/180032/218329798-02c32fb0-015c-4d5b-a42b-33830159a03a.png)

Note that I've also had to make an array of RDUniforms untyped and change `class_name Plane` to `class_name Plane2` to get the GDScript code to work without errors.

**Comment by Nordup** [comment]
I have fixed errors you mentioned, but couldn't reproduce this issue :(
Can you please check if it still remains?

**Comment by Calinou** [comment]
On 500a98610932344ad8c200c1729721ea7fd441b8 with Godot 4.0.rc 15a97a2e8, I still get incorrect rendering:

![image](https://user-images.githubusercontent.com/180032/219904131-2699b092-d44c-4414-a473-a4c82c42f7bc.png)

Which operating system and graphics card model are you using? This could be a vendor-specific difference.

**Comment by Nordup** [comment]
Mangaro with NVIDIA GeForce GTX 1050 (nvidia 525.89.02 drivers)
I will check on another computers. Thank you!

**Comment by atelieralice** [comment]
With RTX 4060 Laptop (tested with driver versions 560.81 and 566.36) I face the same problem above. However, it runs as expected on my friend's GTX 1050 (driver version 561.03).

I asked another friend to test who has an RTX 3050 Laptop and it too ran it fine. This seems to be an issue specific to RTX 40 series GPUs.

**Comment by Nordup** [comment]
I'm not sure why it's green at all
Wish I had some way to reproduce and fix that

**Comment by Calinou** [comment]
Still reproducible on 4.4.stable (Linux, GeForce RTX 4090 with NVIDIA 570.86.16):

![Image](https://github.com/user-attachments/assets/ab66f4eb-7133-4ac6-bff9-3486e892bdeb)

**Comment by Nordup** [comment]
My friend got a new RTX 4060 so I'll hopefully be able to test and fix this soon
